# Generated by Django 2.0.7 on 2018-07-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.Products')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
