# Generated by Django 2.0.7 on 2018-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0003_auto_20180724_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='no_of_parts_used',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
