# Generated by Django 2.0.7 on 2018-08-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0005_auto_20180801_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
