# Generated by Django 2.0.7 on 2018-08-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0006_auto_20180801_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='product_type1',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='product_type1', to='firstPage.Products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='firstPage.Products'),
        ),
    ]
