# Generated by Django 2.0.7 on 2018-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0007_auto_20180801_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallog',
            name='action',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
