# Generated by Django 2.0.7 on 2018-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0008_rawmateriallog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmateriallog',
            name='action',
        ),
    ]
