# Generated by Django 2.0.7 on 2018-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0010_rawmateriallog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='no_of_parts_used',
            field=models.FloatField(),
        ),
    ]
