# Generated by Django 2.0.7 on 2018-08-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0011_auto_20180808_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_parts_used', models.FloatField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.Products')),
            ],
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='no_of_parts_used',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='product_type1',
        ),
        migrations.AddField(
            model_name='rawmaterialmapping',
            name='raw_material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.RawMaterial'),
        ),
    ]
