# Generated by Django 2.0.7 on 2018-08-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0013_auto_20180809_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmateriallog',
            old_name='item_id',
            new_name='raw_material_id',
        ),
        migrations.RemoveField(
            model_name='productlog',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productlog',
            name='product_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='firstPage.Products'),
            preserve_default=False,
        ),
    ]
