# Generated by Django 2.0.7 on 2018-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0014_auto_20180809_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='raw_material_id',
            field=models.IntegerField(),
        ),
    ]
