# Generated by Django 2.0.7 on 2018-08-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0015_auto_20180809_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmateriallog',
            name='raw_material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.RawMaterial'),
        ),
    ]
