# Generated by Django 2.0.7 on 2018-08-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0016_auto_20180809_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmateriallog',
            name='raw_material_id',
            field=models.IntegerField(),
        ),
    ]
