# Generated by Django 2.0.7 on 2018-08-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0018_auto_20180814_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlog',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rawmateriallog',
            old_name='raw_material_id',
            new_name='raw_material',
        ),
    ]
