# Generated by Django 2.0.7 on 2018-08-25 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0020_auto_20180814_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmateriallog',
            name='action',
        ),
        migrations.AddField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
