# Generated by Django 2.0.7 on 2018-08-25 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0021_auto_20180826_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
