# Generated by Django 2.0.7 on 2018-08-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0022_auto_20180826_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
    ]
