# Generated by Django 2.0.7 on 2018-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0023_remove_rawmaterial_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(default='NUMBER', max_length=30),
            preserve_default=False,
        ),
    ]
