# Generated by Django 2.0.7 on 2018-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0026_masterlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='masterlog',
            name='time',
        ),
        migrations.AlterField(
            model_name='masterlog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
