# Generated by Django 2.0.7 on 2018-09-07 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0027_auto_20180908_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlog',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='masterlog',
            name='time',
            field=models.TimeField(default=datetime.datetime.today),
        ),
    ]
