# Generated by Django 2.0.7 on 2018-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0028_auto_20180908_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlog',
            name='time',
            field=models.TimeField(default='02:21:25'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='02:21:25'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='02:21:25'),
        ),
    ]
