# Generated by Django 2.0.7 on 2018-09-08 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0029_auto_20180909_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlog',
            name='time',
            field=models.TimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='02:28:21'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='02:28:21'),
        ),
    ]
