# Generated by Django 2.0.7 on 2018-09-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0030_auto_20180909_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlog',
            name='item_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='03:14:41'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='03:14:41'),
        ),
    ]
