# Generated by Django 2.0.7 on 2019-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0034_auto_20180917_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlog',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default='2019-02-01'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='21:19:27'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default='2019-02-01'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='21:19:27'),
        ),
    ]
