# Generated by Django 2.0.7 on 2019-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0035_auto_20190201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default='2019-03-31'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='00:46:26'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default='2019-03-31'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='00:46:26'),
        ),
    ]
