# Generated by Django 2.0.7 on 2019-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0036_auto_20190331_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='00:57:09'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='00:57:09'),
        ),
    ]
