# Generated by Django 2.0.7 on 2019-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0037_auto_20190331_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='order',
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='01:00:02'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='01:00:02'),
        ),
    ]
