# Generated by Django 2.0.7 on 2019-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0038_auto_20190331_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='01:01:49'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='01:01:49'),
        ),
    ]
