# Generated by Django 2.0.7 on 2019-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0042_auto_20190331_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='isProduct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default='2019-08-11'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='00:09:45'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default='2019-08-11'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='00:09:45'),
        ),
    ]
