# Generated by Django 2.0.7 on 2019-08-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0043_auto_20190811_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isRawMaterial',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='00:35:19'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='00:35:19'),
        ),
    ]
