# Generated by Django 2.0.7 on 2019-08-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0044_auto_20190811_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlog',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.Products'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default='2019-08-15'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='01:33:28'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default='2019-08-15'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='01:33:28'),
        ),
    ]
