# Generated by Django 2.0.7 on 2019-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0045_auto_20190815_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='01:35:56'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='01:35:56'),
        ),
    ]
