# Generated by Django 2.0.7 on 2019-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0046_auto_20190815_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterlog',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(default='2019-08-17'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='time',
            field=models.TimeField(default='22:42:02'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='date',
            field=models.DateField(default='2019-08-17'),
        ),
        migrations.AlterField(
            model_name='rawmateriallog',
            name='time',
            field=models.TimeField(default='22:42:02'),
        ),
    ]
